2023-04-23 16:12:08,324 - INFO: Starting Hydrogen Torch v1.2.0
2023-04-23 16:12:08,390 - INFO: <pre>Sun Apr 23 16:12:08 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   33C    P0    23W / 300W |      2MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
</pre>
2023-04-23 16:12:08,391 - INFO: Global random seed: 949707
2023-04-23 16:12:08,391 - INFO: Preparing the data...
2023-04-23 16:12:08,391 - INFO: Setting up cross-validation...
2023-04-23 16:12:08,412 - INFO: Running k-fold setup...
2023-04-23 16:12:08,873 - INFO: Loading pretrained weights from url (https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth)
2023-04-23 16:12:13,094 - INFO: Preparing train and validation data
2023-04-23 16:12:13,094 - INFO: Loading train dataset...
2023-04-23 16:12:13,098 - INFO: Loading validation dataset...
2023-04-23 16:12:13,101 - INFO: Number of observations in train dataset: 664
2023-04-23 16:12:13,101 - INFO: Number of observations in validation dataset: 165
2023-04-23 16:12:13,107 - INFO: Epoch: 1 / 5
2023-04-23 16:12:13,108 - INFO: train loss:   0%|          | 0/20 [00:00<?, ?it/s]
2023-04-23 16:12:15,562 - INFO: train loss: 0.70:   5%|5         | 1/20 [00:02<00:46,  2.45s/it]
2023-04-23 16:12:15,648 - INFO: train loss: 0.66:  10%|#         | 2/20 [00:02<00:19,  1.06s/it]
2023-04-23 16:12:15,724 - INFO: train loss: 0.63:  15%|#5        | 3/20 [00:02<00:10,  1.64it/s]
2023-04-23 16:12:15,805 - INFO: train loss: 0.60:  20%|##        | 4/20 [00:02<00:06,  2.49it/s]
2023-04-23 16:12:15,886 - INFO: train loss: 0.57:  25%|##5       | 5/20 [00:02<00:04,  3.49it/s]
2023-04-23 16:12:15,980 - INFO: train loss: 0.54:  30%|###       | 6/20 [00:02<00:03,  4.53it/s]
2023-04-23 16:12:16,058 - INFO: train loss: 0.51:  35%|###5      | 7/20 [00:02<00:02,  5.74it/s]
2023-04-23 16:12:16,150 - INFO: train loss: 0.48:  40%|####      | 8/20 [00:03<00:01,  6.75it/s]
2023-04-23 16:12:16,250 - INFO: train loss: 0.46:  45%|####5     | 9/20 [00:03<00:01,  7.51it/s]
2023-04-23 16:12:16,338 - INFO: train loss: 0.44:  50%|#####     | 10/20 [00:03<00:01,  8.39it/s]
2023-04-23 16:12:16,426 - INFO: train loss: 0.39:  55%|#####5    | 11/20 [00:03<00:00,  9.14it/s]
2023-04-23 16:12:16,507 - INFO: train loss: 0.35:  60%|######    | 12/20 [00:03<00:00,  9.93it/s]
2023-04-23 16:12:16,593 - INFO: train loss: 0.31:  65%|######5   | 13/20 [00:03<00:00, 10.38it/s]
2023-04-23 16:12:16,684 - INFO: train loss: 0.27:  70%|#######   | 14/20 [00:03<00:00, 10.53it/s]
2023-04-23 16:12:16,765 - INFO: train loss: 0.25:  75%|#######5  | 15/20 [00:03<00:00, 11.04it/s]
2023-04-23 16:12:16,839 - INFO: train loss: 0.22:  80%|########  | 16/20 [00:03<00:00, 11.66it/s]
2023-04-23 16:12:16,913 - INFO: train loss: 0.20:  85%|########5 | 17/20 [00:03<00:00, 12.16it/s]
2023-04-23 16:12:16,987 - INFO: train loss: 0.19:  90%|######### | 18/20 [00:03<00:00, 12.54it/s]
2023-04-23 16:12:17,062 - INFO: train loss: 0.18:  95%|#########5| 19/20 [00:03<00:00, 12.81it/s]
2023-04-23 16:12:17,136 - INFO: train loss: 0.17: 100%|##########| 20/20 [00:04<00:00, 13.01it/s]
2023-04-23 16:12:17,136 - INFO: train loss: 0.17: 100%|##########| 20/20 [00:04<00:00,  4.97it/s]
2023-04-23 16:12:17,137 - INFO: Starting validation inference
2023-04-23 16:12:17,137 - INFO: validation progress:   0%|          | 0/6 [00:00<?, ?it/s]
2023-04-23 16:12:17,864 - INFO: validation progress:  17%|#6        | 1/6 [00:00<00:03,  1.38it/s]
2023-04-23 16:12:17,900 - INFO: validation progress:  33%|###3      | 2/6 [00:00<00:01,  3.12it/s]
2023-04-23 16:12:17,936 - INFO: validation progress:  50%|#####     | 3/6 [00:00<00:00,  5.26it/s]
2023-04-23 16:12:17,968 - INFO: validation progress:  67%|######6   | 4/6 [00:00<00:00,  7.81it/s]
2023-04-23 16:12:18,001 - INFO: validation progress:  83%|########3 | 5/6 [00:00<00:00, 10.66it/s]
2023-04-23 16:12:18,201 - INFO: validation progress: 100%|##########| 6/6 [00:01<00:00,  7.70it/s]
2023-04-23 16:12:18,203 - INFO: validation progress: 100%|##########| 6/6 [00:01<00:00,  5.63it/s]
2023-04-23 16:12:18,264 - INFO: Mean validation loss: 0.15087
2023-04-23 16:12:18,288 - INFO: Validation ROC_AUC: 0.76133
2023-04-23 16:12:18,309 - ERROR: Stratified random sampling error: 
Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 195, in resolve
    return self.resolvers[key]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'class_vigna'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 206, in resolve
    return self.temps[key]
KeyError: 'class_vigna'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hydrogen_torch_cythonized/hydrogen_torch/src/utils/data_utils.py", line 276, in hydrogen_torch.src.utils.data_utils.stratified_sample_indices
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4111, in query
    res = self.eval(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4240, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 350, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 811, in __init__
    self.terms = self.parse()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 830, in parse
    return self._visitor.visit(self.expr)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 723, in visit_Compare
    return self.visit(binop)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 549, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 98, in __init__
    self._value = self._resolve_name()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 115, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 211, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.core.computation.ops.UndefinedVariableError: name 'class_vigna' is not defined
2023-04-23 16:12:21,272 - INFO: Epoch: 2 / 5
2023-04-23 16:12:21,273 - INFO: train loss:   0%|          | 0/20 [00:00<?, ?it/s]
2023-04-23 16:12:21,843 - INFO: train loss: 0.15:   5%|5         | 1/20 [00:00<00:10,  1.76it/s]
2023-04-23 16:12:21,922 - INFO: train loss: 0.15:  10%|#         | 2/20 [00:00<00:05,  3.56it/s]
2023-04-23 16:12:22,011 - INFO: train loss: 0.15:  15%|#5        | 3/20 [00:00<00:03,  5.16it/s]
2023-04-23 16:12:22,098 - INFO: train loss: 0.15:  20%|##        | 4/20 [00:00<00:02,  6.61it/s]
2023-04-23 16:12:22,333 - INFO: train loss: 0.15:  25%|##5       | 5/20 [00:01<00:02,  5.50it/s]
2023-04-23 16:12:22,448 - INFO: train loss: 0.15:  30%|###       | 6/20 [00:01<00:02,  6.30it/s]
2023-04-23 16:12:22,555 - INFO: train loss: 0.15:  35%|###5      | 7/20 [00:01<00:01,  7.04it/s]
2023-04-23 16:12:22,648 - INFO: train loss: 0.15:  40%|####      | 8/20 [00:01<00:01,  7.91it/s]
2023-04-23 16:12:22,726 - INFO: train loss: 0.15:  45%|####5     | 9/20 [00:01<00:01,  8.99it/s]
2023-04-23 16:12:22,853 - INFO: train loss: 0.15:  50%|#####     | 10/20 [00:01<00:01,  8.61it/s]
2023-04-23 16:12:22,959 - INFO: train loss: 0.15:  55%|#####5    | 11/20 [00:01<00:01,  8.86it/s]
2023-04-23 16:12:23,051 - INFO: train loss: 0.15:  60%|######    | 12/20 [00:01<00:00,  9.37it/s]
2023-04-23 16:12:23,158 - INFO: train loss: 0.15:  65%|######5   | 13/20 [00:01<00:00,  9.36it/s]
2023-04-23 16:12:23,237 - INFO: train loss: 0.15:  70%|#######   | 14/20 [00:01<00:00, 10.17it/s]
2023-04-23 16:12:23,311 - INFO: train loss: 0.15:  75%|#######5  | 15/20 [00:02<00:00, 10.98it/s]
2023-04-23 16:12:23,385 - INFO: train loss: 0.15:  80%|########  | 16/20 [00:02<00:00, 11.65it/s]
2023-04-23 16:12:23,457 - INFO: train loss: 0.15:  85%|########5 | 17/20 [00:02<00:00, 12.23it/s]
2023-04-23 16:12:23,530 - INFO: train loss: 0.15:  90%|######### | 18/20 [00:02<00:00, 12.66it/s]
2023-04-23 16:12:23,603 - INFO: train loss: 0.14:  95%|#########5| 19/20 [00:02<00:00, 12.96it/s]
2023-04-23 16:12:23,678 - INFO: train loss: 0.14: 100%|##########| 20/20 [00:02<00:00, 13.07it/s]
2023-04-23 16:12:23,678 - INFO: train loss: 0.14: 100%|##########| 20/20 [00:02<00:00,  8.32it/s]
2023-04-23 16:12:23,679 - INFO: Starting validation inference
2023-04-23 16:12:23,679 - INFO: validation progress:   0%|          | 0/6 [00:00<?, ?it/s]
2023-04-23 16:12:24,174 - INFO: validation progress:  17%|#6        | 1/6 [00:00<00:02,  2.03it/s]
2023-04-23 16:12:24,209 - INFO: validation progress:  33%|###3      | 2/6 [00:00<00:00,  4.46it/s]
2023-04-23 16:12:24,300 - INFO: validation progress:  50%|#####     | 3/6 [00:00<00:00,  6.11it/s]
2023-04-23 16:12:24,334 - INFO: validation progress:  67%|######6   | 4/6 [00:00<00:00,  8.92it/s]
2023-04-23 16:12:24,436 - INFO: validation progress:  83%|########3 | 5/6 [00:00<00:00,  9.22it/s]
2023-04-23 16:12:24,449 - INFO: validation progress: 100%|##########| 6/6 [00:00<00:00, 13.10it/s]
2023-04-23 16:12:24,451 - INFO: validation progress: 100%|##########| 6/6 [00:00<00:00,  7.77it/s]
2023-04-23 16:12:24,509 - INFO: Mean validation loss: 0.15045
2023-04-23 16:12:24,533 - INFO: Validation ROC_AUC: 0.90524
2023-04-23 16:12:24,550 - ERROR: Stratified random sampling error: 
Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 195, in resolve
    return self.resolvers[key]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'class_vigna'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 206, in resolve
    return self.temps[key]
KeyError: 'class_vigna'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hydrogen_torch_cythonized/hydrogen_torch/src/utils/data_utils.py", line 276, in hydrogen_torch.src.utils.data_utils.stratified_sample_indices
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4111, in query
    res = self.eval(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4240, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 350, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 811, in __init__
    self.terms = self.parse()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 830, in parse
    return self._visitor.visit(self.expr)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 723, in visit_Compare
    return self.visit(binop)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 549, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 98, in __init__
    self._value = self._resolve_name()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 115, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 211, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.core.computation.ops.UndefinedVariableError: name 'class_vigna' is not defined
2023-04-23 16:12:27,424 - INFO: Epoch: 3 / 5
2023-04-23 16:12:27,424 - INFO: train loss:   0%|          | 0/20 [00:00<?, ?it/s]
2023-04-23 16:12:28,004 - INFO: train loss: 0.14:   5%|5         | 1/20 [00:00<00:11,  1.73it/s]
2023-04-23 16:12:28,098 - INFO: train loss: 0.14:  10%|#         | 2/20 [00:00<00:05,  3.40it/s]
2023-04-23 16:12:28,219 - INFO: train loss: 0.14:  15%|#5        | 3/20 [00:00<00:03,  4.65it/s]
2023-04-23 16:12:28,322 - INFO: train loss: 0.14:  20%|##        | 4/20 [00:00<00:02,  5.86it/s]
2023-04-23 16:12:28,433 - INFO: train loss: 0.14:  25%|##5       | 5/20 [00:01<00:02,  6.69it/s]
2023-04-23 16:12:28,553 - INFO: train loss: 0.14:  30%|###       | 6/20 [00:01<00:01,  7.18it/s]
2023-04-23 16:12:28,632 - INFO: train loss: 0.13:  35%|###5      | 7/20 [00:01<00:01,  8.37it/s]
2023-04-23 16:12:28,738 - INFO: train loss: 0.13:  40%|####      | 8/20 [00:01<00:01,  8.69it/s]
2023-04-23 16:12:28,844 - INFO: train loss: 0.13:  45%|####5     | 9/20 [00:01<00:01,  8.90it/s]
2023-04-23 16:12:28,928 - INFO: train loss: 0.13:  50%|#####     | 10/20 [00:01<00:01,  9.65it/s]
2023-04-23 16:12:29,026 - INFO: train loss: 0.13:  55%|#####5    | 11/20 [00:01<00:00,  9.80it/s]
2023-04-23 16:12:29,138 - INFO: train loss: 0.13:  60%|######    | 12/20 [00:01<00:00,  9.53it/s]
2023-04-23 16:12:29,227 - INFO: train loss: 0.13:  65%|######5   | 13/20 [00:01<00:00,  9.99it/s]
2023-04-23 16:12:29,303 - INFO: train loss: 0.13:  70%|#######   | 14/20 [00:01<00:00, 10.78it/s]
2023-04-23 16:12:29,378 - INFO: train loss: 0.13:  75%|#######5  | 15/20 [00:01<00:00, 11.43it/s]
2023-04-23 16:12:29,456 - INFO: train loss: 0.13:  80%|########  | 16/20 [00:02<00:00, 11.79it/s]
2023-04-23 16:12:29,532 - INFO: train loss: 0.13:  85%|########5 | 17/20 [00:02<00:00, 12.21it/s]
2023-04-23 16:12:29,606 - INFO: train loss: 0.13:  90%|######### | 18/20 [00:02<00:00, 12.56it/s]
2023-04-23 16:12:29,680 - INFO: train loss: 0.13:  95%|#########5| 19/20 [00:02<00:00, 12.82it/s]
2023-04-23 16:12:29,754 - INFO: train loss: 0.13: 100%|##########| 20/20 [00:02<00:00, 13.01it/s]
2023-04-23 16:12:29,755 - INFO: train loss: 0.13: 100%|##########| 20/20 [00:02<00:00,  8.58it/s]
2023-04-23 16:12:29,755 - INFO: Starting validation inference
2023-04-23 16:12:29,756 - INFO: validation progress:   0%|          | 0/6 [00:00<?, ?it/s]
2023-04-23 16:12:30,257 - INFO: validation progress:  17%|#6        | 1/6 [00:00<00:02,  2.00it/s]
2023-04-23 16:12:30,291 - INFO: validation progress:  33%|###3      | 2/6 [00:00<00:00,  4.41it/s]
2023-04-23 16:12:30,371 - INFO: validation progress:  50%|#####     | 3/6 [00:00<00:00,  6.27it/s]
2023-04-23 16:12:30,405 - INFO: validation progress:  67%|######6   | 4/6 [00:00<00:00,  9.10it/s]
2023-04-23 16:12:30,553 - INFO: validation progress:  83%|########3 | 5/6 [00:00<00:00,  8.07it/s]
2023-04-23 16:12:30,567 - INFO: validation progress: 100%|##########| 6/6 [00:00<00:00, 11.57it/s]
2023-04-23 16:12:30,569 - INFO: validation progress: 100%|##########| 6/6 [00:00<00:00,  7.38it/s]
2023-04-23 16:12:30,623 - INFO: Mean validation loss: 0.13207
2023-04-23 16:12:30,647 - INFO: Validation ROC_AUC: 0.92265
2023-04-23 16:12:30,664 - ERROR: Stratified random sampling error: 
Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 195, in resolve
    return self.resolvers[key]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'class_vigna'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 206, in resolve
    return self.temps[key]
KeyError: 'class_vigna'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hydrogen_torch_cythonized/hydrogen_torch/src/utils/data_utils.py", line 276, in hydrogen_torch.src.utils.data_utils.stratified_sample_indices
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4111, in query
    res = self.eval(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4240, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 350, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 811, in __init__
    self.terms = self.parse()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 830, in parse
    return self._visitor.visit(self.expr)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 723, in visit_Compare
    return self.visit(binop)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 549, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 98, in __init__
    self._value = self._resolve_name()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 115, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 211, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.core.computation.ops.UndefinedVariableError: name 'class_vigna' is not defined
2023-04-23 16:12:33,735 - INFO: Epoch: 4 / 5
2023-04-23 16:12:33,735 - INFO: train loss:   0%|          | 0/20 [00:00<?, ?it/s]
2023-04-23 16:12:34,553 - INFO: train loss: 0.13:   5%|5         | 1/20 [00:00<00:15,  1.22it/s]
2023-04-23 16:12:34,636 - INFO: train loss: 0.13:  10%|#         | 2/20 [00:00<00:06,  2.59it/s]
2023-04-23 16:12:34,740 - INFO: train loss: 0.13:  15%|#5        | 3/20 [00:01<00:04,  3.89it/s]
2023-04-23 16:12:34,839 - INFO: train loss: 0.12:  20%|##        | 4/20 [00:01<00:03,  5.14it/s]
2023-04-23 16:12:34,953 - INFO: train loss: 0.12:  25%|##5       | 5/20 [00:01<00:02,  6.05it/s]
2023-04-23 16:12:35,050 - INFO: train loss: 0.13:  30%|###       | 6/20 [00:01<00:01,  7.03it/s]
2023-04-23 16:12:35,154 - INFO: train loss: 0.13:  35%|###5      | 7/20 [00:01<00:01,  7.71it/s]
2023-04-23 16:12:35,259 - INFO: train loss: 0.13:  40%|####      | 8/20 [00:01<00:01,  8.21it/s]
2023-04-23 16:12:35,371 - INFO: train loss: 0.13:  45%|####5     | 9/20 [00:01<00:01,  8.41it/s]
2023-04-23 16:12:35,453 - INFO: train loss: 0.13:  50%|#####     | 10/20 [00:01<00:01,  9.31it/s]
2023-04-23 16:12:35,535 - INFO: train loss: 0.13:  55%|#####5    | 11/20 [00:01<00:00, 10.04it/s]
2023-04-23 16:12:35,628 - INFO: train loss: 0.12:  60%|######    | 12/20 [00:01<00:00, 10.23it/s]
2023-04-23 16:12:35,729 - INFO: train loss: 0.12:  65%|######5   | 13/20 [00:01<00:00, 10.15it/s]
2023-04-23 16:12:35,805 - INFO: train loss: 0.12:  70%|#######   | 14/20 [00:02<00:00, 10.90it/s]
2023-04-23 16:12:35,885 - INFO: train loss: 0.12:  75%|#######5  | 15/20 [00:02<00:00, 11.33it/s]
2023-04-23 16:12:35,961 - INFO: train loss: 0.12:  80%|########  | 16/20 [00:02<00:00, 11.82it/s]
2023-04-23 16:12:36,038 - INFO: train loss: 0.12:  85%|########5 | 17/20 [00:02<00:00, 12.18it/s]
2023-04-23 16:12:36,113 - INFO: train loss: 0.12:  90%|######### | 18/20 [00:02<00:00, 12.49it/s]
2023-04-23 16:12:36,196 - INFO: train loss: 0.12:  95%|#########5| 19/20 [00:02<00:00, 12.36it/s]
2023-04-23 16:12:36,270 - INFO: train loss: 0.12: 100%|##########| 20/20 [00:02<00:00, 12.67it/s]
2023-04-23 16:12:36,270 - INFO: train loss: 0.12: 100%|##########| 20/20 [00:02<00:00,  7.89it/s]
2023-04-23 16:12:36,271 - INFO: Starting validation inference
2023-04-23 16:12:36,271 - INFO: validation progress:   0%|          | 0/6 [00:00<?, ?it/s]
2023-04-23 16:12:36,799 - INFO: validation progress:  17%|#6        | 1/6 [00:00<00:02,  1.90it/s]
2023-04-23 16:12:36,834 - INFO: validation progress:  33%|###3      | 2/6 [00:00<00:00,  4.21it/s]
2023-04-23 16:12:36,888 - INFO: validation progress:  50%|#####     | 3/6 [00:00<00:00,  6.49it/s]
2023-04-23 16:12:36,922 - INFO: validation progress:  67%|######6   | 4/6 [00:00<00:00,  9.40it/s]
2023-04-23 16:12:37,093 - INFO: validation progress:  83%|########3 | 5/6 [00:00<00:00,  7.70it/s]
2023-04-23 16:12:37,107 - INFO: validation progress: 100%|##########| 6/6 [00:00<00:00, 11.06it/s]
2023-04-23 16:12:37,109 - INFO: validation progress: 100%|##########| 6/6 [00:00<00:00,  7.17it/s]
2023-04-23 16:12:37,172 - INFO: Mean validation loss: 0.12782
2023-04-23 16:12:37,195 - INFO: Validation ROC_AUC: 0.92909
2023-04-23 16:12:37,213 - ERROR: Stratified random sampling error: 
Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 195, in resolve
    return self.resolvers[key]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'class_vigna'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 206, in resolve
    return self.temps[key]
KeyError: 'class_vigna'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hydrogen_torch_cythonized/hydrogen_torch/src/utils/data_utils.py", line 276, in hydrogen_torch.src.utils.data_utils.stratified_sample_indices
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4111, in query
    res = self.eval(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4240, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 350, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 811, in __init__
    self.terms = self.parse()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 830, in parse
    return self._visitor.visit(self.expr)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 723, in visit_Compare
    return self.visit(binop)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 549, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 98, in __init__
    self._value = self._resolve_name()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 115, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 211, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.core.computation.ops.UndefinedVariableError: name 'class_vigna' is not defined
2023-04-23 16:12:40,073 - INFO: Epoch: 5 / 5
2023-04-23 16:12:40,073 - INFO: train loss:   0%|          | 0/20 [00:00<?, ?it/s]
2023-04-23 16:12:40,702 - INFO: train loss: 0.12:   5%|5         | 1/20 [00:00<00:11,  1.59it/s]
2023-04-23 16:12:40,839 - INFO: train loss: 0.12:  10%|#         | 2/20 [00:00<00:06,  2.95it/s]
2023-04-23 16:12:40,916 - INFO: train loss: 0.12:  15%|#5        | 3/20 [00:00<00:03,  4.56it/s]
2023-04-23 16:12:41,010 - INFO: train loss: 0.12:  20%|##        | 4/20 [00:00<00:02,  5.88it/s]
2023-04-23 16:12:41,164 - INFO: train loss: 0.12:  25%|##5       | 5/20 [00:01<00:02,  6.08it/s]
2023-04-23 16:12:41,246 - INFO: train loss: 0.12:  30%|###       | 6/20 [00:01<00:01,  7.33it/s]
2023-04-23 16:12:41,342 - INFO: train loss: 0.12:  35%|###5      | 7/20 [00:01<00:01,  8.12it/s]
2023-04-23 16:12:41,436 - INFO: train loss: 0.12:  40%|####      | 8/20 [00:01<00:01,  8.78it/s]
2023-04-23 16:12:41,529 - INFO: train loss: 0.12:  45%|####5     | 9/20 [00:01<00:01,  9.31it/s]
2023-04-23 16:12:41,635 - INFO: train loss: 0.12:  50%|#####     | 10/20 [00:01<00:01,  9.37it/s]
2023-04-23 16:12:41,722 - INFO: train loss: 0.12:  55%|#####5    | 11/20 [00:01<00:00,  9.92it/s]
2023-04-23 16:12:41,824 - INFO: train loss: 0.12:  60%|######    | 12/20 [00:01<00:00,  9.89it/s]
2023-04-23 16:12:41,900 - INFO: train loss: 0.12:  65%|######5   | 13/20 [00:01<00:00, 10.68it/s]
2023-04-23 16:12:41,987 - INFO: train loss: 0.12:  70%|#######   | 14/20 [00:01<00:00, 10.94it/s]
2023-04-23 16:12:42,074 - INFO: train loss: 0.12:  75%|#######5  | 15/20 [00:02<00:00, 11.10it/s]
2023-04-23 16:12:42,173 - INFO: train loss: 0.12:  80%|########  | 16/20 [00:02<00:00, 10.77it/s]
2023-04-23 16:12:42,250 - INFO: train loss: 0.12:  85%|########5 | 17/20 [00:02<00:00, 11.35it/s]
2023-04-23 16:12:42,325 - INFO: train loss: 0.12:  90%|######### | 18/20 [00:02<00:00, 11.88it/s]
2023-04-23 16:12:42,401 - INFO: train loss: 0.12:  95%|#########5| 19/20 [00:02<00:00, 12.22it/s]
2023-04-23 16:12:42,481 - INFO: train loss: 0.12: 100%|##########| 20/20 [00:02<00:00, 12.31it/s]
2023-04-23 16:12:42,481 - INFO: train loss: 0.12: 100%|##########| 20/20 [00:02<00:00,  8.30it/s]
2023-04-23 16:12:42,482 - INFO: Starting validation inference
2023-04-23 16:12:42,483 - INFO: validation progress:   0%|          | 0/6 [00:00<?, ?it/s]
2023-04-23 16:12:42,957 - INFO: validation progress:  17%|#6        | 1/6 [00:00<00:02,  2.11it/s]
2023-04-23 16:12:42,991 - INFO: validation progress:  33%|###3      | 2/6 [00:00<00:00,  4.64it/s]
2023-04-23 16:12:43,087 - INFO: validation progress:  50%|#####     | 3/6 [00:00<00:00,  6.21it/s]
2023-04-23 16:12:43,121 - INFO: validation progress:  67%|######6   | 4/6 [00:00<00:00,  9.05it/s]
2023-04-23 16:12:43,232 - INFO: validation progress:  83%|########3 | 5/6 [00:00<00:00,  9.02it/s]
2023-04-23 16:12:43,246 - INFO: validation progress: 100%|##########| 6/6 [00:00<00:00, 12.83it/s]
2023-04-23 16:12:43,248 - INFO: validation progress: 100%|##########| 6/6 [00:00<00:00,  7.84it/s]
2023-04-23 16:12:43,310 - INFO: Mean validation loss: 0.12701
2023-04-23 16:12:43,334 - INFO: Validation ROC_AUC: 0.92946
2023-04-23 16:12:43,352 - ERROR: Stratified random sampling error: 
Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 195, in resolve
    return self.resolvers[key]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'class_vigna'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 206, in resolve
    return self.temps[key]
KeyError: 'class_vigna'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hydrogen_torch_cythonized/hydrogen_torch/src/utils/data_utils.py", line 276, in hydrogen_torch.src.utils.data_utils.stratified_sample_indices
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4111, in query
    res = self.eval(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4240, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 350, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 811, in __init__
    self.terms = self.parse()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 830, in parse
    return self._visitor.visit(self.expr)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 723, in visit_Compare
    return self.visit(binop)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 549, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 98, in __init__
    self._value = self._resolve_name()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 115, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 211, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.core.computation.ops.UndefinedVariableError: name 'class_vigna' is not defined
2023-04-23 16:12:46,240 - INFO: Saving last model checkpoint: val_loss 0.12701, val_ROC_AUC 0.92946 to output/anon/crop-classification/fold4/checkpoint.pth
2023-04-23 16:12:46,428 - INFO: Building MLOps and Scoring Pipeline
2023-04-23 16:12:52,362 - INFO: Running interpretability analysis
2023-04-23 16:12:52,374 - ERROR: Stratified random sampling error: 
Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 195, in resolve
    return self.resolvers[key]
  File "/usr/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'class_vigna'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 206, in resolve
    return self.temps[key]
KeyError: 'class_vigna'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hydrogen_torch_cythonized/hydrogen_torch/src/utils/data_utils.py", line 276, in hydrogen_torch.src.utils.data_utils.stratified_sample_indices
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4111, in query
    res = self.eval(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 4240, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 350, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 811, in __init__
    self.terms = self.parse()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 830, in parse
    return self._visitor.visit(self.expr)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 723, in visit_Compare
    return self.visit(binop)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 536, in visit_BinOp
    op, op_class, left, right = self._maybe_transform_eq_ne(node)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 456, in _maybe_transform_eq_ne
    left = self.visit(node.left, side="left")
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 549, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 98, in __init__
    self._value = self._resolve_name()
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/ops.py", line 115, in _resolve_name
    res = self.env.resolve(self.local_name, is_local=self.is_local)
  File "/resources/venv/lib/python3.8/site-packages/pandas/core/computation/scope.py", line 211, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.core.computation.ops.UndefinedVariableError: name 'class_vigna' is not defined
2023-04-23 16:13:44,208 - INFO: Interpretability analysis completed
